a = input("Type of Dessert: ")
b = input("Silly Word: ")
c = input("Another Word for Father: ")
d = input("Year: ")
e = input("Celebrity: ")
f = input("Type of Plant: ")
g = input("Adjective: ")
h = input("Pet Name: ")
i = input("Name of a Band: ")
j = input("Plural Animal: ")
k = input("Verb (-ing): ")
l = input("Number: ")
m = input("Measurement of Time: ")
n = input("Body Part: ")
o = input("Type of Beer: ")
p = input("Type of Doctor: ")
q = input("One Syllable Noise: ")
r = input("Plural Noun: ")
s = input("Mode of Transportation: ")
t = input("Holiday: ")

print("\n\nELF: Hi Santa.")
print("SANTA: Hello "+a+".")
print("ELF: You’re looking at me like I’m on your naughty list.")
print("SANTA: I was counting my toys and was one "+b+" short. I believe you stole it.")
print("ELF: But "+c+"!")
print("SANTA: I started making that toy in "+d+". What will little "+e+" think when he/she wakes up on Christmas morning\nwith nothing under the "+f+"?")
print("ELF: I would never steal such a "+g+" toy.")
print("SANTA: Where were you the night before Christmas?")
print("ELF: I was with "+h+". We were listening to "+i+"’s holiday album and making snow "+j+".")
print("SANTA: Then why did Rudolph see you "+k+" on the roof "+l+" "+m+" before the toy went missing?")
print("ELF: That’s a coincidence.")
print("SANTA: The reason I work so hard, is because I get to spread joy to millions of people, and go sit by the fire\nshaking my "+n+" while eating cookies and drinking "+o+".")
print("ELF: Fine, I stole the toy. But I only did it because I wanted to impress my "+p+".")
print("SANTA: "+q+", "+q+", "+q+", Every time there’s a holiday miracle, I sing my favorite Christmas song, Jingle "+r+".")
print("(singing)")
print("Jingle "+r+", Jingle "+r+",")
print("Jingle all the way.")
print("Oh what fun it is to ride")
print("In a one horse open "+s+".")
print("ELF: Happy "+t+" Santa!")